apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: sungjin
  annotations:
    "sidecar.istio.io/inject": "false"
spec:
  predictor:
    sklearn:
      image: "kserve/sklearnserver:v0.11.1"
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"