apiVersion: v1
kind: ResourceQuota
metadata:
  name: kf-resource-quota
  namespace: sungjin
spec:
  hard:
    cpu: "8"
    memory: "32Gi"
    persistentvolumeclaims: "10"
    requests.nvidia.com/gpu: "1"
    requests.storage: "100Gi"
